### ISSUE TITLE
Startup crashed

### ISSUE THREAD

**Issue by T1Wgh** [Project-Interactions/Interactions#26]
why?
https://mclo.gs/v4Akpsj
[crash-2023-03-11_15.26.10-client.txt](https://github.com/Project-Interactions/Interactions/files/10947892/crash-2023-03-11_15.26.10-client.txt)

**Comment by mczph** [comment]
did you update any mod?

**Comment by T1Wgh** [comment]
No
话说你是不是中国人啊，中文交流方便点&nbsp;


SKT丶邮箱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月11日(星期六) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Project-Interactions/Interactions] Startup crashed (Issue #26)





 
did you update any mod?

**Comment by mczph** [comment]
是。解决方法删除Extra Sounds模组

**Comment by mczph** [comment]
目前看来原因不明，少部分人崩溃，之后下个版本会更新这个模组，你到时候再试试吧

**Comment by T1Wgh** [comment]
好的，我删除了，可以了。感谢作者带来的Interactions
&nbsp;


SKT丶邮箱
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月11日(星期六) 晚上6:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Project-Interactions/Interactions] Startup crashed (Issue #26)





 
目前看来原因不明，少部分人崩溃，之后下个版本会更新这个模组，你到时候再试试吧
