### ISSUE TITLE
The mouse doesn't work.

### ISSUE THREAD

**Issue by gavinops** [Project-Interactions/Interactions#29]
It works kinda I can select and create worlds but move the player's camera? N O. Help would be much appreciated thank you!

**Comment by mczph** [comment]
You may need to try /rescan, if it doesn't work or you are using a MacOS system, you need to delete the rawinput mod.

**Comment by gavinops** [comment]
I'll test it and report back after testing.

**Comment by gavinops** [comment]
It worked. Thank you for the help!
