### ISSUE TITLE
[Bug]When enter a world, a CrT error occurred.

### ISSUE THREAD

**Issue by LingJiuQiSan** [Project-Interactions/Interactions#33]
log: `[Client thread/INFO]: [CHAT] §c[crafttweaker | SIDE_CLIENT]: Error parsing recipes\mods\LC.zs:17 -- ; expected` .
I think this is because [scripts/recipes/mods/LC.zs Line 15](https://github.com/Project-Interactions/Interactions/blob/1ff01652f5630c7febcd08c929184961ba0cd080/scripts/recipes/mods/LC.zs#L15) missing a ";" .

**Comment by LingJiuQiSan** [comment]
Interactions Version: 1.64, downloaded from github release.

**Comment by mczph** [comment]
is my problem, just don't have time to release a new version (the 1.64 version of curseforge is already archived.

**Comment by mczph** [comment]
Fixed,please recheck github or curseforge
